In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import style
style.use('ggplot')

import datetime as dt
import bs4 as bs
import robin_stocks as r
import requests
import lxml
from lxml import etree


We need to make this work with all sets of data from certain lists in Robinhood. 
Next Steps:
-Log in to Robhin hood
-Use Beatiful Soup to Scrape the ticker list of: 
    - 100 Most Popular
    - Top Movers
    - Index ETFs
    - Crypto

In [2]:
# getting ticker list of  100 most popular
resp = requests.get('https://robinhood.com/collections/100-most-popular')
# soup = bs.BeautifulSoup(resp.text, 'lxml') # parse into soup object
soup = bs.BeautifulSoup(resp.content, 'html.parser')
table = soup.find("table", {"class": "_25eGUhpRN5n6jaWqzmSOZl table"})

In [3]:
tickers = []

for row in table.findAll('tr')[1:]:
    ticker = row.findAll('td')[1].text
    tickers.append(ticker)

In [4]:
names = []

for row in table.findAll('tr')[1:]:
    name = row.findAll('td')[0].text
    names.append(name)

['CPRX',
 'CRBP',
 'BABA',
 'SNE',
 'APHA',
 'GOOGL',
 'MSFT',
 'AMZN',
 'NRZ',
 'PTON',
 'PYPL',
 'NKE',
 'V',
 'UBER',
 'GM',
 'FB',
 'KO',
 'MRNA',
 'NVDA',
 'PLUG',
 'TXMD',
 'ZNGA',
 'WMT',
 'JNJ',
 'NTDOY',
 'DKNG',
 'ET',
 'PENN',
 'GE',
 'JPM',
 'DIS',
 'NFLX',
 'AZN',
 'AAPL',
 'LYFT',
 'BP',
 'SNAP',
 'LUV',
 'NOK',
 'DAL',
 'BAC',
 'PFE',
 'WORK',
 'SIRI',
 'NIO',
 'ZM',
 'SBUX',
 'AMD',
 'SQ',
 'SAVE',
 'HAL',
 'KOS',
 'BA',
 'GILD',
 'UAL',
 'BRK.B',
 'NCLH',
 'INTC',
 'T',
 'RCL',
 'MRO',
 'RKT',
 'INO',
 'JBLU',
 'WFC',
 'CRON',
 'CGC',
 'MGM',
 'TSLA',
 'ACB',
 'AAL',
 'BYND',
 'TWTR',
 'F',
 'GPRO',
 'MFA',
 'PLAY',
 'GPS',
 'XOM',
 'TLRY',
 'CCL',
 'FIT',
 'NKLA',
 'AMC',
 'SPCE',
 'VOO',
 'GUSH',
 'WKHS',
 'USO',
 'IVR',
 'SPY',
 'UCO',
 'VSLR',
 'IBIO',
 'SPHD',
 'PSEC',
 'KODK',
 'SRNE',
 'FCEL',
 'NVAX']

In [149]:
# converting ticker list to csv
df_tickers = pd.DataFrame(tickers)
df_tickers.columns = ['TickerLabel']
df_tickers.to_csv('robinhood_data/ticker_lists/100_most_popular.csv')

In [150]:
for ticker in tickers:
    ticker_str = str(ticker)
    data = r.stocks.get_stock_historicals(ticker_str,interval='day', span='5year', bounds='regular')
    df = pd.DataFrame(data)
    df.to_csv('robinhood_data/stock_spreadsheets/{}.csv'.format(ticker_str))

Compile the csvs into one csv using pickle, we only need the close_price and beings_at columns

In [151]:
import pickle

In [157]:
tickers.sort()
tickers

['AAL',
 'AAPL',
 'ACB',
 'AMC',
 'AMD',
 'AMZN',
 'APHA',
 'BA',
 'BABA',
 'BAC',
 'BP',
 'BRK.B',
 'BYND',
 'CCL',
 'CGC',
 'CPRX',
 'CRBP',
 'CRON',
 'DAL',
 'DIS',
 'DKNG',
 'ET',
 'F',
 'FB',
 'FCEL',
 'FIT',
 'GE',
 'GILD',
 'GM',
 'GNUS',
 'GOOGL',
 'GPRO',
 'GPS',
 'GUSH',
 'HAL',
 'IBIO',
 'INO',
 'INTC',
 'IVR',
 'JBLU',
 'JNJ',
 'JPM',
 'KO',
 'KODK',
 'KOS',
 'LUV',
 'LYFT',
 'MFA',
 'MGM',
 'MRNA',
 'MRO',
 'MSFT',
 'NCLH',
 'NFLX',
 'NIO',
 'NKE',
 'NKLA',
 'NOK',
 'NRZ',
 'NVAX',
 'NVDA',
 'NYMT',
 'PENN',
 'PFE',
 'PLAY',
 'PLUG',
 'PSEC',
 'PTON',
 'PYPL',
 'RCL',
 'SAVE',
 'SBUX',
 'SIRI',
 'SNAP',
 'SNE',
 'SPCE',
 'SPHD',
 'SPY',
 'SQ',
 'SRNE',
 'T',
 'TLRY',
 'TOPS',
 'TSLA',
 'TWTR',
 'TXMD',
 'UAL',
 'UBER',
 'UCO',
 'USO',
 'V',
 'VOO',
 'VSLR',
 'WFC',
 'WKHS',
 'WMT',
 'WORK',
 'XOM',
 'ZM',
 'ZNGA']

In [161]:
df = pd.read_csv('robinhood_data/stock_spreadsheets/{}.csv'.format(tickers[0]))
df.head()

,Unnamed: 0,begins_at,open_price,close_price,high_price,low_price,volume,session,interpolated,symbol
0,0,2015-08-13T00:00:00Z,42.76,42.67,43.275,42.27,6605820,reg,False,AAL
1,1,2015-08-14T00:00:00Z,42.35,42.88,43.170,42.35,4857867,reg,False,AAL
2,2,2015-08-17T00:00:00Z,42.96,43.95,44.015,42.82,8385397,reg,False,AAL
3,3,2015-08-18T00:00:00Z,44.06,43.63,44.450,43.24,6317183,reg,False,AAL
4,4,2015-08-19T00:00:00Z,43.53,43.53,44.270,43.21,8373959,reg,False,AAL

In [165]:
main_df = pd.DataFrame()

for count, ticker in enumerate(tickers):
    df = pd.read_csv('robinhood_data/stock_spreadsheets/{}.csv'.format(ticker))
    df.drop(['Unnamed: 0'], axis=1, inplace=True)
    df.set_index('begins_at', inplace=True)
    df.rename(columns={'close_price': ticker}, inplace=True)
    df.drop(['open_price', 'high_price', 'low_price', 'volume',
             'session', 'interpolated', 'symbol'], 
            axis=1, inplace=True)
    
    if main_df.empty:
        main_df = df
    
    else:
        main_df = main_df.join(df, how='outer')
        
    main_df.to_csv('robinhood_data/100_most_popular.csv')